### ISSUE TITLE
Б16. Выбран подходящий формат изображений.

### ISSUE THREAD

**Issue by zeckson** [zeckson/html-nerds#14]
Неправильный формат изображений:
- должен быть png и без фона (фон должен быть сделан при помощи CSS):
a-prezentacii.jpg 
a-prilogeniya.jpg
a-saiti.jpg

- должен быть полупрозрачный PNG:
img-present.jpg
m-gallery1.jpg
vk-icon.jpg

**Comment by KirillGrant** [comment]
в макете они jpg
что страшного если они останутся jpg?

**Comment by zeckson** [comment]
Давай посмотрим вместе. Я когда писал, там была причина, почему это стоит переделать

**Comment by zeckson** [comment]
Сошлись на том, что картинки с фонами ошибки дизайнера и решили не исправлять
