### ISSUE TITLE
Б4. Грубые ошибки в разметке отсутствуют.

### ISSUE THREAD

**Issue by zeckson** [zeckson/html-nerds#5]
Кнопки `заказать` должн либо быть ссылками (пункт 1), либо быть обернуты тэгом <fom> (пункт 4):
![image](https://user-images.githubusercontent.com/259739/70914936-3ee9c380-2019-11ea-90b1-58d61b27721b.png)
Использован тэг `<br>` вместо `<p>`:
![image](https://user-images.githubusercontent.com/259739/70915830-e1ef0d00-201a-11ea-8bc3-e193043351a6.png)
Разрешённые места (https://up.htmlacademy.ru/htmlcss/17/examples_br)
Так же тут разбито тэгом, `<p>`, хотя в этом случае явно рекомендован `<br>` (пункт 3):
```html
      <p>191186 Санкт-Петербург</p>
      <p>ул Б.Конюшенная, д.19\8</p>
      <p>тел.+7(812)00-00-0</p>
```

**Comment by KirillGrant** [comment]
done

**Comment by zeckson** [comment]
Есть несколько замечаний:
1. Тэг `<p>` не может быть одиночным — это создаёт новые ошибки вёрстки. В следующих местах:
- https://github.com/zeckson/html-nerds/pull/16/commits/c8f0bab89ab98824bbfaa8a3bd4b0d6ffe6dca82#diff-eacf331f0ffc35d4b482f1d15a887d3bR79
- https://github.com/zeckson/html-nerds/pull/16/commits/c8f0bab89ab98824bbfaa8a3bd4b0d6ffe6dca82#diff-eacf331f0ffc35d4b482f1d15a887d3bR73
- https://github.com/zeckson/html-nerds/pull/16/commits/c8f0bab89ab98824bbfaa8a3bd4b0d6ffe6dca82#diff-eacf331f0ffc35d4b482f1d15a887d3bR67


2. Тэг `<br>` не может быть двойным:
https://github.com/zeckson/html-nerds/commit/c8f0bab89ab98824bbfaa8a3bd4b0d6ffe6dca82#diff-d4345ee549d438d51c0cba47c34ab25cR145

3. Тэг `<br>` обычно используется в связке с тэгом `<p>`:
Смотри правильный пример в (https://up.htmlacademy.ru/htmlcss/17/criteries#basic-4) в третьем пункте:
```
<p>191186,<br>
Санкт-Петербург,<br>
Большая Конюшенная, 19/8
</p>
```

**Comment by zeckson** [comment]
Тэг `<span>` сломан:  https://github.com/zeckson/html-nerds/pull/16/commits/c8f0bab89ab98824bbfaa8a3bd4b0d6ffe6dca82#diff-eacf331f0ffc35d4b482f1d15a887d3bR103

**Comment by zeckson** [comment]
Исправлено
